In [12]:
import pandas as pd

In [13]:
df = pd.read_csv("wine_data.csv")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12

In [14]:
df.head(-10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,10.17,0.28,0.42,2.6,0.087,9.6,26.3,0.99802,3.20,0.78,10.68,6,206,Domaine Riesling Estate 271,2022-06-16
206,9.03,0.43,0.40,1.3,0.070,22.5,48.3,0.99664,3.31,0.85,10.76,6,207,Domaine Cabernet Estate 566,2022-06-03
207,11.02,0.46,0.32,2.3,0.075,22.7,38.0,0.99783,3.35,0.83,9.98,5,208,Domaine Merlot Premium 462,2024-08-20
208,10.13,0.40,0.45,1.2,0.078,10.5,23.9,0.99725,3.30,0.73,10.74,6,209,Villa Merlot Estate 296,2023-08-03
209,11.69,0.53,0.50,2.4,0.062,17.8,45.3,0.99593,3.19,0.77,11.05,6,210,Bodega Sauvignon Premium 73,2023-04-24

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         220 non-null    float64
 1   volatile acidity      220 non-null    float64
 2   citric acid           220 non-null    float64
 3   residual sugar        220 non-null    float64
 4   chlorides             220 non-null    float64
 5   free sulfur dioxide   220 non-null    float64
 6   total sulfur dioxide  220 non-null    float64
 7   density               220 non-null    float64
 8   pH                    220 non-null    float64
 9   sulphates             220 non-null    float64
 10  alcohol               220 non-null    float64
 11  quality               220 non-null    int64
 12  Id                    220 non-null    int64
 13  name                  220 non-null    object
 14  date                  220 non-null    object
dtypes: float64(11), int64(2), object(2)
memory usage: 25.9+ KB

In [23]:
df.name.str.title()

0                                Winea
1                                Wineb
2                                Winec
3                                Wined
4            Weingut Syrah Reserve 575
                    ...
215           Bodega Pinot Classic 513
216       Castello Merlot Grand Cru 41
217    Bodega Chardonnay Grand Cru 257
218       Chateau Cabernet Special 857
219       Bodega Sauvignon Classic 591
Name: name, Length: 220, dtype: object

In [24]:
df.name.str.len()

0       5
1       5
2       5
3       5
4      25
       ..
215    24
216    28
217    31
218    28
219    28
Name: name, Length: 220, dtype: int64

In [25]:
df[df.name.str.contains('A')]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date
0,8.5,0.28,0.56,1.8,0.092,35.0,103.0,0.9969,3.3,0.75,10.5,7,16,WineA,2023-01-10

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         220 non-null    float64
 1   volatile acidity      220 non-null    float64
 2   citric acid           220 non-null    float64
 3   residual sugar        220 non-null    float64
 4   chlorides             220 non-null    float64
 5   free sulfur dioxide   220 non-null    float64
 6   total sulfur dioxide  220 non-null    float64
 7   density               220 non-null    float64
 8   pH                    220 non-null    float64
 9   sulphates             220 non-null    float64
 10  alcohol               220 non-null    float64
 11  quality               220 non-null    int64
 12  Id                    220 non-null    int64
 13  name                  220 non-null    object
 14  date                  220 non-null    object
dtypes: float64(11), int64(2), object(2)
memory usage: 25.9+ KB

In [28]:
df.date.dtype

dtype('O')

In [31]:
df['date'] = pd.to_datetime(df.date)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         220 non-null    float64
 1   volatile acidity      220 non-null    float64
 2   citric acid           220 non-null    float64
 3   residual sugar        220 non-null    float64
 4   chlorides             220 non-null    float64
 5   free sulfur dioxide   220 non-null    float64
 6   total sulfur dioxide  220 non-null    float64
 7   density               220 non-null    float64
 8   pH                    220 non-null    float64
 9   sulphates             220 non-null    float64
 10  alcohol               220 non-null    float64
 11  quality               220 non-null    int64
 12  Id                    220 non-null    int64
 13  name                  220 non-null    object
 14  date                  220 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(11), int64(2), object(1)
memory usage: 25.9+ KB

In [35]:
df['year']=df.date.dt.year
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,year
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10,2023
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15,2023
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20,2023
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25,2023
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12,2023

In [36]:
df['month']=df.date.dt.month
df['day']=df.date.dt.day
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,year,month,day
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10,2023,1,10
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15,2023,2,15
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20,2023,3,20
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25,2023,4,25
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12,2023,2,12

#### **Add new data**

In [43]:
df.loc[len(df)] = [10,0.34, 0.17, 2.1, 0.1, 23, 56, 0.778, 2.8, 0.98, 42, 8, 981, 'Gold monk', '2022-09-11', '2022','09','10']
df.loc[len(df) - 1]

fixed acidity                 10.0
volatile acidity              0.34
citric acid                   0.17
residual sugar                 2.1
chlorides                      0.1
free sulfur dioxide           23.0
total sulfur dioxide          56.0
density                      0.778
pH                             2.8
sulphates                     0.98
alcohol                       42.0
quality                          8
Id                             981
name                     Gold monk
date                    2022-09-11
year                          2022
month                           09
day                             10
Name: 222, dtype: object

#### **Delete Data**

In [ ]:
# delete one index
df.drop(index = 4, inplace=True)
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,year,month,day
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15 00:00:00,2023,2,15
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20 00:00:00,2023,3,20
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25 00:00:00,2023,4,25
5,8.72,0.56,0.34,0.8,0.059,22.3,59.8,0.99571,3.35,0.79,9.79,4,6,Bodega Riesling Special 559,2024-05-09 00:00:00,2024,5,9
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,3.32,0.73,9.15,4,7,Domaine Pinot Grand Cru 285,2022-01-14 00:00:00,2022,1,14

In [57]:
# delete multiple rows
df.drop(index=[2,3,5,88,91], inplace=True)
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,year,month,day
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15 00:00:00,2023,2,15
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,3.32,0.73,9.15,4,7,Domaine Pinot Grand Cru 285,2022-01-14 00:00:00,2022,1,14
7,9.08,0.63,0.49,1.1,0.072,18.1,42.5,0.99795,3.20,0.81,8.88,3,8,Domaine Riesling Premium 349,2023-07-24 00:00:00,2023,7,24
8,8.88,0.44,0.40,2.9,0.079,15.3,43.6,0.99742,3.42,0.79,10.84,5,9,Domaine Cabernet Classic 105,2022-07-09 00:00:00,2022,7,9
9,9.31,0.55,0.29,2.4,0.078,18.5,39.4,0.99652,3.24,0.76,8.97,3,10,Castello Merlot Classic 868,2023-12-06 00:00:00,2023,12,6

In [ ]:
df.drop(columns=['year','day','month'], inplace= True)
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15 00:00:00
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,3.32,0.73,9.15,4,7,Domaine Pinot Grand Cru 285,2022-01-14 00:00:00
7,9.08,0.63,0.49,1.1,0.072,18.1,42.5,0.99795,3.20,0.81,8.88,3,8,Domaine Riesling Premium 349,2023-07-24 00:00:00
8,8.88,0.44,0.40,2.9,0.079,15.3,43.6,0.99742,3.42,0.79,10.84,5,9,Domaine Cabernet Classic 105,2022-07-09 00:00:00
9,9.31,0.55,0.29,2.4,0.078,18.5,39.4,0.99652,3.24,0.76,8.97,3,10,Castello Merlot Classic 868,2023-12-06 00:00:00

In [63]:
df['High_Alchohol'] = df.alcohol >= 10
df.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,High_Alchohol
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15 00:00:00,True
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,3.32,0.73,9.15,4,7,Domaine Pinot Grand Cru 285,2022-01-14 00:00:00,False
7,9.08,0.63,0.49,1.1,0.072,18.1,42.5,0.99795,3.20,0.81,8.88,3,8,Domaine Riesling Premium 349,2023-07-24 00:00:00,False
8,8.88,0.44,0.40,2.9,0.079,15.3,43.6,0.99742,3.42,0.79,10.84,5,9,Domaine Cabernet Classic 105,2022-07-09 00:00:00,True
9,9.31,0.55,0.29,2.4,0.078,18.5,39.4,0.99652,3.24,0.76,8.97,3,10,Castello Merlot Classic 868,2023-12-06 00:00:00,False
10,7.53,0.43,0.59,2.2,0.075,23.4,60.0,0.99553,3.23,0.77,10.06,5,11,Weingut Chardonnay Reserve 748,2024-07-29 00:00:00,True
11,7.50,0.65,0.61,3.9,0.090,17.2,32.1,0.99597,3.27,0.88,9.82,3,12,Weingut Merlot Premium 81,2023-08-24 00:00:00,False
12,8.68,0.69,0.39,2.3,0.069,9.3,22.9,0.99688,3.34,0.71,9.98,4,13,Bodega Syrah Classic 592,2023-01-29 00:00:00,False
13,10.58,0.45,0.32,2.4,0.091,8.9,14.7,0.99702,3.13,0.87,9.94,5,14,Bodega Merlot Reserve 678,2023-04-12 00:00:00,False
14,9.43,0.51,0.57,2.9,0.096,21.9,64.8,0.99660,3.18,0.70,10.58,5,15,Villa Merlot Estate 888,2022-07-26 00:00:00,True

In [64]:
df['wine_type'] = 'Red Wine'
df.head(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date,High_Alchohol,wine_type
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15 00:00:00,True,Red Wine
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,3.32,0.73,9.15,4,7,Domaine Pinot Grand Cru 285,2022-01-14 00:00:00,False,Red Wine
7,9.08,0.63,0.49,1.1,0.072,18.1,42.5,0.99795,3.20,0.81,8.88,3,8,Domaine Riesling Premium 349,2023-07-24 00:00:00,False,Red Wine
8,8.88,0.44,0.40,2.9,0.079,15.3,43.6,0.99742,3.42,0.79,10.84,5,9,Domaine Cabernet Classic 105,2022-07-09 00:00:00,True,Red Wine
9,9.31,0.55,0.29,2.4,0.078,18.5,39.4,0.99652,3.24,0.76,8.97,3,10,Castello Merlot Classic 868,2023-12-06 00:00:00,False,Red Wine

#### **Merge and Concatinate**

In [68]:
data1 = {
    'Name':['A','B','C'],
    'age':[21,45,32],
    'salary':[10000, 200000, 60000000]
}

data2 = {
     'Name':['A1','B1','C'],
    'age':[56,35,45],
    'salary':[75288, 455555, 987668865]
}

new_df1 = pd.DataFrame(data1)
new_df2 = pd.DataFrame(data2)

In [69]:
new_df1.head()

  Name  age    salary
0    A   21     10000
1    B   45    200000
2    C   32  60000000

In [70]:
new_df2.head()

  Name  age     salary
0   A1   56      75288
1   B1   35     455555
2    C   45  987668865

In [71]:
pd.concat([new_df1, new_df2], ignore_index=True)

  Name  age     salary
0    A   21      10000
1    B   45     200000
2    C   32   60000000
3   A1   56      75288
4   B1   35     455555
5    C   45  987668865

In [72]:
pd.concat([new_df1, new_df2], ignore_index=True, axis = 1)

   0   1         2   3   4          5
0  A  21     10000  A1  56      75288
1  B  45    200000  B1  35     455555
2  C  32  60000000   C  45  987668865

In [73]:
new_df = pd.concat([new_df1, new_df2], ignore_index=True)

In [76]:
new_df.drop_duplicates(inplace=True)
new_df.head()

  Name  age    salary
0    A   21     10000
1    B   45    200000
2    C   32  60000000
3   A1   56     75288
4   B1   35    455555

#### **Merge**

In [80]:
pd.merge(new_df1, new_df2, on='salary', how='outer')

  Name_x  age_x     salary Name_y  age_y
0      A   21.0      10000    NaN    NaN
1    NaN    NaN      75288     A1   56.0
2      B   45.0     200000    NaN    NaN
3    NaN    NaN     455555     B1   35.0
4      C   32.0   60000000    NaN    NaN
5    NaN    NaN  987668865      C   45.0